# Generated by Django 5.2.5 on 2025-08-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
    ]
